version: "3.8"

services:
  # ==============================
  # 🧠 n8n (Workflow Automation)
  # ==============================
  n8n:
    image: n8nio/n8n:1.115.3
    restart: always
    env_file:
      - .env
    environment:
      - N8N_HOST=n8n.finalnews.qzz.io
      - WEBHOOK_TUNNEL_URL=https://n8n.finalnews.qzz.io
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      # These ensure clean logs and timezone alignment
      - GENERIC_TIMEZONE=Africa/Lagos
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_net

  # ==============================
  # 🗄️ PostgreSQL Database
  # ==============================
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - n8n_db_data:/var/lib/postgresql/data
    networks:
      - n8n_net

  # ==============================
  # 🌐 Caddy Reverse Proxy (HTTPS)
  # ==============================
  caddy:
    image: caddy:2.8
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - n8n
    networks:
      - n8n_net

# ==============================
# 🔗 Networks & Volumes
# ==============================
networks:
  n8n_net:

volumes:
  n8n_data:
  n8n_db_data:
  caddy_data:
  caddy_config:
